just commit

diff --git a/src/cat/Makefile b/src/cat/Makefile
--- a/src/cat/Makefile
+++ b/src/cat/Makefile
@@ -1,45 +1,49 @@
 CC=gcc
-CFLAGS=-std=c11 -Wall -Werror -Wextra -g 
+CFLAGS=-std=c11 -Wall -Werror -Wextra
 LDFLAGS=-g
 MATHFLAG=-lm
 TARGET=main
 SHELL:=/bin/bash
 FILE=test.txt
 CHECK=2>&1 valgrind --tool=memcheck --leak-check=yes
-PREF_DIR=../build
-.PHONY: all cat clean
+.PHONY: all cat_run clean
 
-all: 
+all: clean cat_run tests
 
-s21_cat:
-		$(CC)  $(CFLAGS) test_cat.c cat.c $(LDFLAGS) -o s21_cat
+cat_run:
+		$(CC)  $(CFLAGS) test_cat.c cat.c $(LDFLAGS) -o s21_cat.out
 
 tests:
-		-diff <(./s21_cat $(FILE)) <(cat $(FILE))
-		-diff <(./s21_cate -e $(FILE)) <(cat -e $(FILE))
-		# -diff <(./s21_cat -n $(FILE)) <(cat -n $(FILE))
-		# -diff <(./s21_cat -b $(FILE)) <(cat -b $(FILE))
-		# -diff <(./s21_cats -s $(FILE)) <(cat -s $(FILE))
-		# -diff <(./s21_cat -t $(FILE)) <(cat -t $(FILE))
-		# -diff <(./s21_cat --number-nonblank $(FILE)) <(cat -b $(FILE))
-		# -diff <(./s21_cat --number $(FILE)) <(cat -n $(FILE))
+		diff <(./s21_cat.out $(FILE)) <(cat $(FILE))
+		if [ $? -eq 0 ]; then
+			echo "SUCCES!"
+		else 
+			echo "FAIL!"
+		fi
+		# -diff <(./s21_cat.out -e $(FILE)) <(cat -e $(FILE))
+		# -diff <(./s21_cat.out -n $(FILE)) <(cat -n $(FILE))
+		# -diff <(./s21_cat.out -b $(FILE)) <(cat -b $(FILE))
+		# -diff <(./s21_cat.outs -s $(FILE)) <(cat -s $(FILE))
+		# -diff <(./s21_cat.out -t $(FILE)) <(cat -t $(FILE))
+		# -diff <(./s21_cat.out --number-nonblank $(FILE)) <(cat -b $(FILE))
+		# -diff <(./s21_cat.out --number $(FILE)) <(cat -n $(FILE))
 		# -diff <(./s21_can --squeeze-blank $(FILE)) <(cat -s $(FILE))
-		# -diff <(./s21_cat -etsnb $(FILE)) <(cat -etsnb $(FILE))
+		# -diff <(./s21_cat.out -etsnb $(FILE)) <(cat -etsnb $(FILE))
 
-		# $(CHECK) ./s21_cat $(FILE) | grep ERROR
-		# $(CHECK) ./s21_cat -n $(FILE) | grep ERROR
-		# $(CHECK) ./s21_cat -e $(FILE) | grep ERROR
-		# $(CHECK) ./s21_cat -s $(FILE) | grep ERROR
-		# $(CHECK) ./s21_cat -b $(FILE) | grep ERROR
-		# $(CHECK) ./s21_cat -t $(FILE) | grep ERROR
-		# $(CHECK) ./s21_cat -tnesb $(FILE) | grep ERROR
+		# $(CHECK) ./s21_cat.out $(FILE) | grep ERROR
+		# $(CHECK) ./s21_cat.out -n $(FILE) | grep ERROR
+		# $(CHECK) ./s21_cat.out -e $(FILE) | grep ERROR
+		# $(CHECK) ./s21_cat.out -s $(FILE) | grep ERROR
+		# $(CHECK) ./s21_cat.out -b $(FILE) | grep ERROR
+		# $(CHECK) ./s21_cat.out -t $(FILE) | grep ERROR
+		# $(CHECK) ./s21_cat.out -tnesb $(FILE) | grep ERROR
 
 clean: 
-		rm ../build/* 
+		rm *.out
 
 leaks_linux:
-		valgrind --tool=memcheck --leak-check=yes ./s21_cat
+		valgrind --tool=memcheck --leak-check=yes ./s21_cat.out
 
 leaks_mac_os:
-		leaks -atExit -- ./s21_cat
+		leaks -atExit -- ./s21_cat.out
 
